version: '2'

services:
  redis:
    image: redis:alpine
    networks:
        - default
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis

  db:
    image: postgres:alpine
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes_from:
      - data
    networks:
      - default
      
  data:
    image: alpine:latest
    volumes:
      - /var/lib/postgresql/data/pgdata
      - /srv/static
      - /srv/media
    command: echo "Data container doing its job!"