# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 22:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('when_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiftEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('duration', models.DurationField()),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('when_modified', models.DateTimeField(auto_now=True)),
                ('lift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Lift')),
            ],
            options={
                'verbose_name_plural': 'Lift Entries',
            },
        ),
        migrations.CreateModel(
            name='RunEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.DurationField()),
                ('elevation_delta', models.DecimalField(decimal_places=2, max_digits=7)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('when_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Run Entries',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_num', models.SmallIntegerField()),
                ('num_reps', models.SmallIntegerField()),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('when_modified', models.DateTimeField(auto_now=True)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LiftEntry')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('when_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='runentry',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Workout'),
        ),
        migrations.AddField(
            model_name='liftentry',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Workout'),
        ),
    ]
