# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_liftentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liftentry',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
