# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 04:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170605_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='liftentry',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 5, 4, 1, 42, 726889)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runentry',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 5, 4, 1, 49, 386835)),
            preserve_default=False,
        ),
    ]
