# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 04:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170605_0419'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RunEntry',
            new_name='Run',
        ),
        migrations.RemoveField(
            model_name='liftentry',
            name='lift',
        ),
        migrations.RemoveField(
            model_name='liftentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='set',
            name='log_entry',
        ),
        migrations.AddField(
            model_name='set',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 5, 4, 37, 54, 573640)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='lift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Lift'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LiftEntry',
        ),
    ]
