# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 21:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_auto_20170605_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiftEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('when_modified', models.DateTimeField(auto_now=True)),
                ('lift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Lift')),
            ],
            options={
                'verbose_name_plural': 'Lift Entries',
            },
        ),
        migrations.CreateModel(
            name='RunEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('when_modified', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.DurationField()),
                ('elevation_delta', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name_plural': 'Run Entries',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('when_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='run',
            name='user',
        ),
        migrations.RemoveField(
            model_name='set',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='set',
            name='lift',
        ),
        migrations.AddField(
            model_name='set',
            name='weight',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Run',
        ),
        migrations.AddField(
            model_name='runentry',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Workout'),
        ),
        migrations.AddField(
            model_name='liftentry',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Workout'),
        ),
        migrations.AddField(
            model_name='set',
            name='lift_entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.LiftEntry'),
            preserve_default=False,
        ),
    ]
