# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170605_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='liftentry',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
