# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170711_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='set_num',
        ),
    ]
