# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_set_set_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liftentry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runentry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
