# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170911_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('when_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('elevation_delta', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
