# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_run_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='runentry',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Run'),
        ),
    ]
