# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 21:17
# Customized by Dan :)

from __future__ import unicode_literals

from django.conf import settings
from django.contrib.auth.models import User
from django.db import migrations, models
import django.db.models.deletion

from api.models import Run

default_user_id = User.objects.first().id
default_run_id = Run.objects.first().id

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_copy_runs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runentry',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='runentry',
            name='elevation_delta',
        ),
        migrations.AlterField(
            model_name='run',
            name='user',
            field=models.ForeignKey(default=default_user_id, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='runentry',
            name='run',
            field=models.ForeignKey(default=default_run_id, on_delete=django.db.models.deletion.CASCADE, to='api.Run'),
        ),
    ]
